version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      # trigger rebuild of web content
      - run:
          name: trigger build
          command: "curl -X POST --header \"Content-Type: application/json\" https://circleci.com/api/v1.1/project/${TARGET_VCS}/${TARGET_USERNAME}/:${TARGET_PROJECT}/build?circle-token=${CIRCLE_API_KEY}"
          
