version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      # trigger rebuild of web content
      - run:
          name: trigger build
          command: sh .circleci/trigger.sh
